### ISSUE TITLE
Percent alignment is off-center in IE. 100% overlaps the circle

### ISSUE THREAD

**Issue by murone** [PredixDev/px-percent-circle#3]
In IE, the % value is off-center to the left. This is just frustrating but can be dealt with for lower numbers, but at 100% the value actually touches the edge of the circle. 

Details: IE11, Windows 10. 

See attached screenshot. Was able to recreate both in my code and by manipulating the properties on predix-ui.com

![image](https://cloud.githubusercontent.com/assets/8251140/21124999/44987c98-c0b0-11e6-8b6a-723be938263e.png)

![image](https://cloud.githubusercontent.com/assets/8251140/21125024/7d46e656-c0b0-11e6-9ec9-301f080f4b48.png)

**Comment by randyaskin** [comment]
Hmm I can't find any way to fix this that doesn't then break it by the same amount in the other browsers. I could mitigate it by reducing the text size (thereby increasing the space between label and circle) but I just can't figure out exactly _what_ IE has implemented incorrectly. Open to suggestions / ideas...

**Comment by murone** [comment]
I can't pinpoint it either but I do notice that removing the % seems to fix the issue. I also notice if I move the % before the # there is a substantial gap between the two (ie: a trailing whitespace on the % character).

Not sure if that helps at all :/
